import asyncio
import discord
import random

from discord.ext import commands

client = commands.Bot(command_prefix="!")

@client.event
async def on_ready():
    print("Bot is ready to use!")

@client.event
async def on_message(message):
    if message.author == client.user:
        return
    elif message.content.startswith("?gather"):
        await client.send_message(message.channel, random.choice([ "What the...? A **Perfectly Round Pebble** sits by your paws! *(1 point)*",
                                                                   "A crunchy noise pricks your ears. You look to find some **Shed Snake Skin** under your paws. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Mouse Skull**! *(4 points)*",
                                                                   "Something glimmers in the corner of your eye. **Locust Wings**! Nice find! *(5 points)*",
                                                                   "A cluster of woven sticks falls from a nearby tree. It appears to be an **Empty Bird's Nest**. Nice find! *(2 points)*",
                                                                   "Some **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                   "A **Hawk Feather** brushes by your paws. How lucky! *(3 points)*",
                                                                   "Your eyes search until they land upon an **Empty Carapace**. Good job! *(2 points)*",
                                                                   "A black wing flutters in the wind. A **Ripped Bat Wing**! *(2 points)*",
                                                                   "A slimey object appears before you. A **Torn Toad Leg**! *(1 point)*",
                                                                   "Ouch! Your paw brushes by a **Cactus Spine!** *(1 point)*",
                                                                   "A pretty flower twirls towards you. It appears to be a **White Cactus Flower**. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Worn Fox Tooth**! *(4 points)*",
                                                                   "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                   "A red rock sits oddly amongst the stones. It's some **Red Sandstone**! *(4 points)*",
                                                                   "Your paws carry your towards a **Desert Goldflower**! Nice find! *(1 point)*",
                                                                   "Your eyes search until they land upon a **Sand Verbano Flower**. Good job! *(2 points)*",
                                                                   "A funny looking rock catches your eye from afar. It appears to be some **Ancient Limestone**. *(5 points)*",
                                                                   "Hmm? Your paws brush by a **Living Stones** plant. Good thing you didn't step on it! *(4 points)*",
                                                                   "What the...? A **Perfectly Round Pebble** sits by your paws! *(1 point)*",
                                                                   "A crunchy noise pricks your ears. You look to find some **Shed Snake Skin** under your paws. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Mouse Skull**! *(4 points)*",
                                                                   "Something glimmers in the corner of your eye. **Locust Wings**! Nice find! *(5 points)*",
                                                                   "A cluster of woven sticks falls from a nearby tree. It appears to be an **Empty Bird's Nest**. Nice find! *(2 points)*",
                                                                   "Some **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                   "A **Hawk Feather** brushes by your paws. How lucky! *(3 points)*",
                                                                   "Your eyes search until they land upon an **Empty Carapace**. Good job! *(2 points)*",
                                                                   "A black wing flutters in the wind. A **Ripped Bat Wing**! *(2 points)*",
                                                                   "A slimey object appears before you. A **Torn Toad Leg**! *(1 point)*",
                                                                   "Ouch! Your paw brushes by a **Cactus Spine!** *(1 point)*",
                                                                   "A pretty flower twirls towards you. It appears to be a **White Cactus Flower**. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Worn Fox Tooth**! *(4 points)*",
                                                                   "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                   "A red rock sits oddly amongst the stones. It's some **Red Sandstone**! *(4 points)*",
                                                                   "Your paws carry your towards a **Desert Goldflower**! Nice find! *(1 point)*",
                                                                   "Your eyes search until they land upon a **Sand Verbano Flower**. Good job! *(2 points)*",
                                                                   "A funny looking rock catches your eye from afar. It appears to be some **Ancient Limestone**. *(5 points)*",
                                                                   "Hmm? Your paws brush by a **Living Stones** plant. Good thing you didn't step on it! *(4 points)*",
                                                                   "What the...? A **Perfectly Round Pebble** sits by your paws! *(1 point)*",
                                                                   "A crunchy noise pricks your ears. You look to find some **Shed Snake Skin** under your paws. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Mouse Skull**! *(4 points)*",
                                                                   "Something glimmers in the corner of your eye. **Locust Wings**! Nice find! *(5 points)*",
                                                                   "A cluster of woven sticks falls from a nearby tree. It appears to be an **Empty Bird's Nest**. Nice find! *(2 points)*",
                                                                   "Some **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                   "A **Hawk Feather** brushes by your paws. How lucky! *(3 points)*",
                                                                   "Your eyes search until they land upon an **Empty Carapace**. Good job! *(2 points)*",
                                                                   "A black wing flutters in the wind. A **Ripped Bat Wing**! *(2 points)*",
                                                                   "A slimey object appears before you. A **Torn Toad Leg**! *(1 point)*",
                                                                   "Ouch! Your paw brushes by a **Cactus Spine!** *(1 point)*",
                                                                   "A pretty flower twirls towards you. It appears to be a **White Cactus Flower**. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Worn Fox Tooth**! *(4 points)*",
                                                                   "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                   "A red rock sits oddly amongst the stones. It's some **Red Sandstone**! *(4 points)*",
                                                                   "Your paws carry your towards a **Desert Goldflower**! Nice find! *(1 point)*",
                                                                   "Your eyes search until they land upon a **Sand Verbano Flower**. Good job! *(2 points)*",
                                                                   "A funny looking rock catches your eye from afar. It appears to be some **Ancient Limestone**. *(5 points)*",
                                                                   "Hmm? Your paws brush by a **Living Stones** plant. Good thing you didn't step on it! *(4 points)*",
                                                                   "What the...? A **Perfectly Round Pebble** sits by your paws! *(1 point)*",
                                                                   "A crunchy noise pricks your ears. You look to find some **Shed Snake Skin** under your paws. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Mouse Skull**! *(4 points)*",
                                                                   "Something glimmers in the corner of your eye. **Locust Wings**! Nice find! *(5 points)*",
                                                                   "A cluster of woven sticks falls from a nearby tree. It appears to be an **Empty Bird's Nest**. Nice find! *(2 points)*",
                                                                   "Some **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                   "A **Hawk Feather** brushes by your paws. How lucky! *(3 points)*",
                                                                   "Your eyes search until they land upon an **Empty Carapace**. Good job! *(2 points)*",
                                                                   "A black wing flutters in the wind. A **Ripped Bat Wing**! *(2 points)*",
                                                                   "A slimey object appears before you. A **Torn Toad Leg**! *(1 point)*",
                                                                   "Ouch! Your paw brushes by a **Cactus Spine!** *(1 point)*",
                                                                   "A pretty flower twirls towards you. It appears to be a **White Cactus Flower**. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Worn Fox Tooth**! *(4 points)*",
                                                                   "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                   "A red rock sits oddly amongst the stones. It's some **Red Sandstone**! *(4 points)*",
                                                                   "Your paws carry your towards a **Desert Goldflower**! Nice find! *(1 point)*",
                                                                   "Your eyes search until they land upon a **Sand Verbano Flower**. Good job! *(2 points)*",
                                                                   "A funny looking rock catches your eye from afar. It appears to be some **Ancient Limestone**. *(5 points)*",
                                                                   "Hmm? Your paws brush by a **Living Stones** plant. Good thing you didn't step on it! *(4 points)*",
                                                                   "What the...? A **Perfectly Round Pebble** sits by your paws! *(1 point)*",
                                                                   "A crunchy noise pricks your ears. You look to find some **Shed Snake Skin** under your paws. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Mouse Skull**! *(4 points)*",
                                                                   "Something glimmers in the corner of your eye. **Locust Wings**! Nice find! *(5 points)*",
                                                                   "A cluster of woven sticks falls from a nearby tree. It appears to be an **Empty Bird's Nest**. Nice find! *(2 points)*",
                                                                   "Some **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                   "A **Hawk Feather** brushes by your paws. How lucky! *(3 points)*",
                                                                   "Your eyes search until they land upon an **Empty Carapace**. Good job! *(2 points)*",
                                                                   "A black wing flutters in the wind. A **Ripped Bat Wing**! *(2 points)*",
                                                                   "A slimey object appears before you. A **Torn Toad Leg**! *(1 point)*",
                                                                   "Ouch! Your paw brushes by a **Cactus Spine!** *(1 point)*",
                                                                   "A pretty flower twirls towards you. It appears to be a **White Cactus Flower**. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Worn Fox Tooth**! *(4 points)*",
                                                                   "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                   "A red rock sits oddly amongst the stones. It's some **Red Sandstone**! *(4 points)*",
                                                                   "Your paws carry your towards a **Desert Goldflower**! Nice find! *(1 point)*",
                                                                   "Your eyes search until they land upon a **Sand Verbano Flower**. Good job! *(2 points)*",
                                                                   "A funny looking rock catches your eye from afar. It appears to be some **Ancient Limestone**. *(5 points)*",
                                                                   "Hmm? Your paws brush by a **Living Stones** plant. Good thing you didn't step on it! *(4 points)*",
                                                                   "What the...? A **Perfectly Round Pebble** sits by your paws! *(1 point)*",
                                                                   "A crunchy noise pricks your ears. You look to find some **Shed Snake Skin** under your paws. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Mouse Skull**! *(4 points)*",
                                                                   "Something glimmers in the corner of your eye. **Locust Wings**! Nice find! *(5 points)*",
                                                                   "A cluster of woven sticks falls from a nearby tree. It appears to be an **Empty Bird's Nest**. Nice find! *(2 points)*",
                                                                   "Some **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                   "A **Hawk Feather** brushes by your paws. How lucky! *(3 points)*",
                                                                   "Your eyes search until they land upon an **Empty Carapace**. Good job! *(2 points)*",
                                                                   "A black wing flutters in the wind. A **Ripped Bat Wing**! *(2 points)*",
                                                                   "A slimey object appears before you. A **Torn Toad Leg**! *(1 point)*",
                                                                   "Ouch! Your paw brushes by a **Cactus Spine!** *(1 point)*",
                                                                   "A pretty flower twirls towards you. It appears to be a **White Cactus Flower**. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Worn Fox Tooth**! *(4 points)*",
                                                                   "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                   "A red rock sits oddly amongst the stones. It's some **Red Sandstone**! *(4 points)*",
                                                                   "Your paws carry your towards a **Desert Goldflower**! Nice find! *(1 point)*",
                                                                   "Your eyes search until they land upon a **Sand Verbano Flower**. Good job! *(2 points)*",
                                                                   "A funny looking rock catches your eye from afar. It appears to be some **Ancient Limestone**. *(5 points)*",
                                                                   "Hmm? Your paws brush by a **Living Stones** plant. Good thing you didn't step on it! *(4 points)*",
                                                                   "What the...? A **Perfectly Round Pebble** sits by your paws! *(1 point)*",
                                                                   "A crunchy noise pricks your ears. You look to find some **Shed Snake Skin** under your paws. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Mouse Skull**! *(4 points)*",
                                                                   "Something glimmers in the corner of your eye. **Locust Wings**! Nice find! *(5 points)*",
                                                                   "A cluster of woven sticks falls from a nearby tree. It appears to be an **Empty Bird's Nest**. Nice find! *(2 points)*",
                                                                   "Some **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                   "A **Hawk Feather** brushes by your paws. How lucky! *(3 points)*",
                                                                   "Your eyes search until they land upon an **Empty Carapace**. Good job! *(2 points)*",
                                                                   "A black wing flutters in the wind. A **Ripped Bat Wing**! *(2 points)*",
                                                                   "A slimey object appears before you. A **Torn Toad Leg**! *(1 point)*",
                                                                   "Ouch! Your paw brushes by a **Cactus Spine!** *(1 point)*",
                                                                   "A pretty flower twirls towards you. It appears to be a **White Cactus Flower**. *(3 points)*",
                                                                   "A small ivory shape stands out amongst the clumps of dirt. It's a **Worn Fox Tooth**! *(4 points)*",
                                                                   "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                   "A red rock sits oddly amongst the stones. It's some **Red Sandstone**! *(4 points)*",
                                                                   "Your paws carry your towards a **Desert Goldflower**! Nice find! *(1 point)*",
                                                                   "Your eyes search until they land upon a **Sand Verbano Flower**. Good job! *(2 points)*",
                                                                   "A funny looking rock catches your eye from afar. It appears to be some **Ancient Limestone**. *(5 points)*",
                                                                   "Hmm? Your paws brush by a **Living Stones** plant. Good thing you didn't step on it! *(4 points)*",
                                                                   "A flash of gold stands out on the rocks. A **Rusted Gold Chain**! *(10 points)*",
                                                                   "An interesting pattern caught your eye. It looks to be an **Ancient Fossil Shell**. *(10 points)*",
                                                                   "Ouch! You step on a **Severed Hawk Talon**! Nice find! *(8 points)*",
                                                                   "A hint of pink stands out in the sand. A **Pink Cactus Flower**! *(7 points)*",
                                                                   "A large white object sits between some tree roots. A **Coyote Skull**! *(8 points)*",
                                                                   "An **Emerald Carapace** shines in the sun. What luck! *(6 points)*",
                                                                   "What's this? A **Fallen Skink Tail** was blown in your direction by the wind. *(6 points)*",
                                                                   "Shiny! Some **Wind-Polished Agate** catches your attention from afar. *(7 points)*",
                                                                   "After some searching, you find some **Cat's Eye Chrysoberyl** hidden between some rocks. Good find! *(7 points)*",
                                                                   "There's something stuck to the cactus beside you. It appears to be a **Butcherbird Larder**. Nice! *(9 points)*",
                                                                   "Your paws brush by a cruchy object. A **Rattlesnake Rattle**! Good thing there's no snake to go along with it. *(9 points)*",
                                                                   "A flash of gold stands out on the rocks. A **Rusted Gold Chain**! *(10 points)*",
                                                                   "An interesting pattern caught your eye. It looks to be an **Ancient Fossil Shell**. *(10 points)*",
                                                                   "Ouch! You step on a **Severed Hawk Talon**! Nice find! *(8 points)*",
                                                                   "A hint of pink stands out in the sand. A **Pink Cactus Flower**! *(7 points)*",
                                                                   "A large white object sits between some tree roots. A **Coyote Skull**! *(8 points)*",
                                                                   "An **Emerald Carapace** shines in the sun. What luck! *(6 points)*",
                                                                   "What's this? A **Fallen Skink Tail** was blown in your direction by the wind. *(6 points)*",
                                                                   "Shiny! Some **Wind-Polished Agate** catches your attention from afar. *(7 points)*",
                                                                   "After some searching, you find some **Cat's Eye Chrysoberyl** hidden between some rocks. Good find! *(7 points)*",
                                                                   "There's something stuck to the cactus beside you. It appears to be a **Butcherbird Larder**. Nice! *(9 points)*",
                                                                   "Your paws brush by a cruchy object. A **Rattlesnake Rattle**! Good thing there's no snake to go along with it. *(9 points)*",
                                                                   "A flash of gold stands out on the rocks. A **Rusted Gold Chain**! *(10 points)*",
                                                                   "An interesting pattern caught your eye. It looks to be an **Ancient Fossil Shell**. *(10 points)*",
                                                                   "Ouch! You step on a **Severed Hawk Talon**! Nice find! *(8 points)*",
                                                                   "A hint of pink stands out in the sand. A **Pink Cactus Flower**! *(7 points)*",
                                                                   "A large white object sits between some tree roots. A **Coyote Skull**! *(8 points)*",
                                                                   "An **Emerald Carapace** shines in the sun. What luck! *(6 points)*",
                                                                   "What's this? A **Fallen Skink Tail** was blown in your direction by the wind. *(6 points)*",
                                                                   "Shiny! Some **Wind-Polished Agate** catches your attention from afar. *(7 points)*",
                                                                   "After some searching, you find some **Cat's Eye Chrysoberyl** hidden between some rocks. Good find! *(7 points)*",
                                                                   "There's something stuck to the cactus beside you. It appears to be a **Butcherbird Larder**. Nice! *(9 points)*",
                                                                   "Your paws brush by a cruchy object. A **Rattlesnake Rattle**! Good thing there's no snake to go along with it. *(9 points)*",
                                                                   "Something golden sits amongst the wild flowers beside you. A **Forgotten Golden Coin**! *(12 points)*",
                                                                   "Thank Starclan! A **Chunk of Quartz** hides between some rocks. *(14 points)*",
                                                                   "Bless Starclan! A **Chunk of Cinnabar** hides between some rocks. *(15 points)*",
                                                                   "Oops! You stepped on a rock half-buried in the sand. It looks like a **Buried Hag Stone**. *(11 points)*",
                                                                   "How lucky! A **Elaborate Ruby Necklace** sits amongst the large rocks. *(13 points)*",
                                                                   "Your eyes catch on something resting on a bulby cactus... It's so small... What could it be...? Oh my! What a rare find! You obtain a **Glimmering Golden Tortoise Beetle**! *(50 points)*",
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"
                                                                   "Gotcha! A **Squirming Horned Lizard** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some movement flashes in the corner of your eye. You act quickly and catch a **Leaping Leopard Gecko**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Some scuttling catches your attention. A **Scuttling Scarab Beetle** hurries away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                   "Oh no! You leap onto a boulder, knocking over some loose rocks. You look down to find that it has crushed a Pinching Scorpion. It's not worth anything, but someone may want it...? (0 points)"]))

client.run("NTQzNTYyNjczMDMyMjY1NzQz.Dz-2Tg.odSGxfaDJMjBkpVY7C86cNdwEx0")
client.login(process.env.BOT_TOKEN);
